[tracery]
grammar = "hellmark.json"

[llm]
model = "/home/llanphar/src/text-generation-webui/models/Wizard-Vicuna-30B-Uncensored.ggmlv3.q4_K_M.bin"
prompt_pre = "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.\n\n### Human: "
prompt_post = "\n### Assistant: "
#prompt_pre = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: "
#prompt_post = " ASSISTANT: "
n_gpu_layers = 100
